<?php

$editorialPages = [
    'house' => [
        'type' => 'story',
        'title' => 'The House of Carat Street',
        'eyebrow' => 'Our House',
        'intro' => 'A modern jewellery house where Indian artistry, thoughtful design and quiet confidence meet.',
        'hero' => 'assets/web/story-celebration-banner.webp',
        'hero_position' => 'center 36%',
        'statement_label' => 'Made With Meaning',
        'statement_title' => 'Jewellery for the life you are creating.',
        'statement_copy' => ['Carat Street approaches jewellery as something deeply personal: a marker of becoming, belonging and celebration.', 'Our visual language balances the richness of Indian adornment with clean, contemporary proportion. The result is expressive without excess and designed to feel entirely your own.'],
        'feature_image' => 'assets/web/jewellery-styling-model.webp',
        'feature_label' => 'A Distinct Point Of View',
        'feature_title' => 'Rooted in heritage. Designed for now.',
        'feature_copy' => 'We look to enduring forms, luminous stones and the emotional rituals surrounding jewellery, then refine them through a modern lens. Every detail has a reason to be there.',
        'chapters_title' => 'The codes of our house',
        'chapters' => [
            ['01', 'Modern Indian Luxury', 'Cultural richness expressed through restraint, balance and a contemporary sensibility.'],
            ['02', 'Personal Expression', 'Pieces intended to become part of a wearer\'s own language, memories and milestones.'],
            ['03', 'Considered Beauty', 'Thoughtful proportions, tactile details and a standard of finish that rewards a closer look.'],
        ],
        'quote' => 'The most precious jewellery does more than complete a look. It holds a story.',
        'notes_title' => 'Our promise',
        'notes' => [
            ['Design with intention', 'Every silhouette begins with clarity of purpose, comfort and character.'],
            ['Clarity in every detail', 'Materials, care and product information should be communicated with honesty.'],
            ['A personal experience', 'Guidance should feel considered, calm and centred on the person choosing the piece.'],
        ],
        'cta_title' => 'Discover the Carat Street world',
        'cta_copy' => 'Explore pieces made for everyday rituals and unforgettable chapters.',
        'cta_href' => 'category.php',
        'cta_label' => 'Explore Collections',
    ],
    'philosophy' => [
        'type' => 'story',
        'title' => 'Our Philosophy',
        'eyebrow' => 'Beauty With Intention',
        'intro' => 'We believe luxury is felt in the thought behind an object, the confidence it gives and the meaning it gathers over time.',
        'hero' => 'assets/web/hero-pearl-editorial.webp',
        'hero_position' => 'center 42%',
        'statement_label' => 'Our Perspective',
        'statement_title' => 'Less about occasion. More about connection.',
        'statement_copy' => ['Jewellery can honour a milestone, but it can also elevate an ordinary morning. We design for both: the grand celebration and the private ritual.', 'Proportion, wearability and emotional resonance guide every choice, so beauty never feels separate from the person wearing it.'],
        'feature_image' => 'assets/web/hero-charm-editorial.webp',
        'feature_label' => 'Quiet Confidence',
        'feature_title' => 'Presence without excess.',
        'feature_copy' => 'Our pieces are composed to catch light, invite attention and still leave room for the wearer. The jewellery speaks, but it never overwhelms.',
        'chapters_title' => 'What guides us',
        'chapters' => [
            ['01', 'Meaning', 'A piece should feel connected to a memory, intention or expression of self.'],
            ['02', 'Balance', 'Rich materials meet disciplined form, creating jewellery with clarity and ease.'],
            ['03', 'Longevity', 'We favour enduring silhouettes over passing spectacle and encourage thoughtful care.'],
        ],
        'quote' => 'True luxury is the freedom to choose what feels unmistakably yours.',
        'notes_title' => 'Designed around you',
        'notes' => [
            ['For daily rituals', 'Refined forms that feel natural from morning to evening.'],
            ['For meaningful moments', 'Jewellery that brings intention to gifting and celebration.'],
            ['For personal style', 'Versatile pieces made to be layered, repeated and reinterpreted.'],
        ],
        'cta_title' => 'Find your expression',
        'cta_copy' => 'Discover jewellery with character, clarity and a story waiting to become yours.',
        'cta_href' => 'category.php',
        'cta_label' => 'View Jewellery',
    ],
    'craftsmanship' => [
        'type' => 'story',
        'title' => 'Craftsmanship',
        'eyebrow' => 'The Art Behind The Piece',
        'intro' => 'From first line to final polish, considered craftsmanship transforms precious materials into jewellery with presence.',
        'hero' => 'assets/web/category-rings-hand.webp',
        'hero_position' => 'center 48%',
        'statement_label' => 'Made In Details',
        'statement_title' => 'Precision you can see. Comfort you can feel.',
        'statement_copy' => ['A successful piece begins with proportion: how a setting holds light, how a curve follows the body and how every surface meets the next.', 'Craft is not a decorative final step. It is the discipline connecting the idea, the material and the experience of wearing the finished piece.'],
        'feature_image' => 'assets/web/diamond-pendant-alternate.webp',
        'feature_label' => 'From Sketch To Finish',
        'feature_title' => 'Each stage has its own purpose.',
        'feature_copy' => 'Design development, material selection, setting, finishing and inspection work together. The smallest decisions shape the final balance and brilliance.',
        'chapters_title' => 'A considered process',
        'chapters' => [
            ['01', 'Form', 'The silhouette is refined for visual balance, movement and ease of wear.'],
            ['02', 'Setting', 'Stones are positioned to support security, symmetry and the intended play of light.'],
            ['03', 'Finish', 'Edges, joins and surfaces are examined so the piece feels resolved from every angle.'],
        ],
        'quote' => 'Craftsmanship is where an idea earns its permanence.',
        'notes_title' => 'What to notice',
        'notes' => [
            ['Proportion', 'A balanced relationship between stone, setting, chain and negative space.'],
            ['Surface', 'A consistent polish and carefully resolved transitions between components.'],
            ['Wearability', 'Secure closures, thoughtful weight and a silhouette designed to sit naturally.'],
        ],
        'cta_title' => 'See craftsmanship in every detail',
        'cta_copy' => 'Explore the collection and look closer at the forms, finishes and settings.',
        'cta_href' => 'category.php',
        'cta_label' => 'Explore Jewellery',
    ],
    'diamond-guide' => [
        'type' => 'guide',
        'title' => 'The Diamond Guide',
        'eyebrow' => 'Understanding Brilliance',
        'intro' => 'A clear introduction to the qualities that shape a diamond\'s beauty, character and presence.',
        'hero' => 'assets/web/hero-diamond-models.webp',
        'hero_position' => 'center 38%',
        'statement_label' => 'Begin With The Four Cs',
        'statement_title' => 'Beauty is a balance, not a single grade.',
        'statement_copy' => ['Cut, colour, clarity and carat weight provide a shared language for comparing diamonds. They are most useful when considered together.', 'Two stones with similar specifications can still present differently. Proportion, light performance and personal preference remain essential.'],
        'feature_image' => 'assets/web/sculpted-diamond-pendant.webp',
        'feature_label' => 'Light And Proportion',
        'feature_title' => 'Cut gives light a path.',
        'feature_copy' => 'The precision of a diamond\'s facets influences how light enters, returns and moves across the stone. A beautifully balanced cut can create brightness, fire and scintillation.',
        'chapters_title' => 'The four qualities',
        'chapters' => [
            ['01', 'Cut', 'The arrangement and proportion of facets that shape light performance.'],
            ['02', 'Colour', 'A scale describing the relative absence of body colour in many diamonds.'],
            ['03', 'Clarity & Carat', 'Clarity considers internal and surface characteristics; carat records weight, not visible size alone.'],
        ],
        'quote' => 'The right diamond is the one whose light, proportion and character feel right to you.',
        'notes_title' => 'Choosing with confidence',
        'notes' => [
            ['Compare in context', 'View stones in the setting style and metal colour you are considering.'],
            ['Look beyond size', 'Spread, cut quality and proportion affect how large and lively a stone appears.'],
            ['Review documentation', 'Ask what grading information accompanies the stone and how its details can be verified.'],
        ],
        'cta_title' => 'Explore diamond jewellery',
        'cta_copy' => 'See how proportion, setting and light come together in finished pieces.',
        'cta_href' => 'category.php',
        'cta_label' => 'View The Collection',
    ],
    'gold-guide' => [
        'type' => 'guide',
        'title' => 'The Gold Guide',
        'eyebrow' => 'A Precious Foundation',
        'intro' => 'Understand purity, colour and wearability before choosing the gold that suits your jewellery and your life.',
        'hero' => 'assets/web/jewellery-styling-model.webp',
        'hero_position' => 'center 42%',
        'statement_label' => 'Gold In Context',
        'statement_title' => 'Purity is only one part of the decision.',
        'statement_copy' => ['Pure gold is naturally rich in colour and highly malleable. Jewellery alloys combine gold with other metals to create different levels of strength, tone and suitability for wear.', 'The best choice depends on the piece, how often it will be worn and the colour that feels most natural against your skin.'],
        'feature_image' => 'assets/web/countdown-statement-necklace.webp',
        'feature_label' => 'Colour And Character',
        'feature_title' => 'Yellow, rose and white each tell light differently.',
        'feature_copy' => 'Alloy composition influences colour. Yellow gold retains traditional warmth, rose gold introduces copper-toned softness, and white gold offers a cooler, modern appearance.',
        'chapters_title' => 'How to choose',
        'chapters' => [
            ['01', 'Purity', 'Higher karat values contain a greater proportion of gold; lower karats generally provide added hardness.'],
            ['02', 'Colour', 'Consider undertone, existing jewellery and whether you prefer warmth, blush or a cool finish.'],
            ['03', 'Lifestyle', 'Think about frequency of wear, contact with surfaces and the care a particular finish may require.'],
        ],
        'quote' => 'Gold becomes personal through the colour, form and memories it carries.',
        'notes_title' => 'A thoughtful checklist',
        'notes' => [
            ['Read the purity mark', 'Look for the stated karat and fineness rather than relying on colour alone.'],
            ['Ask about finish', 'Polished, matte and plated surfaces can age differently and need different care.'],
            ['Store with care', 'Keep pieces dry and separated to reduce tangling, rubbing and surface marks.'],
        ],
        'cta_title' => 'Discover gold with presence',
        'cta_copy' => 'Explore warm, sculptural forms designed to become part of your signature.',
        'cta_href' => 'category.php',
        'cta_label' => 'Explore Gold Jewellery',
    ],
    'everyday-luxury' => [
        'type' => 'collection',
        'title' => 'Everyday Luxury',
        'eyebrow' => 'The Daily Edit',
        'intro' => 'Effortless pieces with enough character for every day and enough presence for everything after.',
        'hero' => 'assets/web/hero-charm-editorial.webp',
        'hero_position' => 'center 48%',
        'statement_label' => 'Designed To Live In',
        'statement_title' => 'Small rituals. Lasting expression.',
        'statement_copy' => ['Everyday luxury is not about saving beauty for later. It is the pleasure of wearing something considered, personal and quietly luminous now.', 'These are versatile silhouettes made to move between work, celebration and the moments in between.'],
        'feature_image' => 'assets/web/pearl-necklace-product.webp',
        'feature_label' => 'Easy By Design',
        'feature_title' => 'Refined alone. Expressive together.',
        'feature_copy' => 'Wear one piece as a point of light or build a composition through layering. The collection is designed to work with your wardrobe and with itself.',
        'chapters_title' => 'The everyday wardrobe',
        'chapters' => [
            ['01', 'Light Layers', 'Fine chains and pendants that create dimension without feeling heavy.'],
            ['02', 'Modern Essentials', 'Clean forms with distinctive details that reward repeated wear.'],
            ['03', 'Personal Combinations', 'Pieces that invite mixing, stacking and a styling language of your own.'],
        ],
        'quote' => 'Wear the special piece on an ordinary day. That is what makes the day yours.',
        'notes_title' => 'Style it your way',
        'notes' => [
            ['Begin with one focal point', 'Let a pendant, ring or earring establish the mood.'],
            ['Vary scale', 'Combine fine and substantial forms to create rhythm without clutter.'],
            ['Repeat a detail', 'A shared metal tone or shape can make layered pieces feel intentional.'],
        ],
        'cta_title' => 'Make every day your occasion',
        'cta_copy' => 'Find versatile jewellery for the way you dress, move and celebrate.',
        'cta_href' => 'category.php',
        'cta_label' => 'Shop The Edit',
    ],
    'signature-collection' => [
        'type' => 'collection',
        'title' => 'Signature Collection',
        'eyebrow' => 'Distinctly Carat Street',
        'intro' => 'Sculptural silhouettes, luminous stones and confident details compose our most recognisable expression.',
        'hero' => 'assets/web/hero-statement-earrings.webp',
        'hero_position' => 'center 38%',
        'statement_label' => 'A Stronger Point Of View',
        'statement_title' => 'Created to be remembered.',
        'statement_copy' => ['Signature jewellery is defined by more than scale. It is the clarity of the idea, the confidence of the proportion and the way a piece changes how you carry yourself.', 'Each design is intended to hold attention while remaining connected to the person wearing it.'],
        'feature_image' => 'assets/web/diamond-pendant-product.webp',
        'feature_label' => 'The Signature Codes',
        'feature_title' => 'Light, line and sculptural contrast.',
        'feature_copy' => 'Curving metal, precise geometry and concentrated brilliance create tension and balance. The result feels polished, expressive and unmistakably modern.',
        'chapters_title' => 'A collection with presence',
        'chapters' => [
            ['01', 'Sculptural Form', 'Silhouettes designed to be recognised from across a room and appreciated up close.'],
            ['02', 'Luminous Focus', 'Stones and reflective surfaces placed to create a deliberate centre of light.'],
            ['03', 'Modern Heirlooms', 'Enduring forms intended to gather personal meaning through wear and memory.'],
        ],
        'quote' => 'A signature piece does not follow the room. It changes it.',
        'notes_title' => 'Choose your signature',
        'notes' => [
            ['Consider the silhouette', 'Look for the shape that feels most natural to your personal style.'],
            ['Balance the composition', 'Let a statement piece lead, then keep supporting jewellery restrained.'],
            ['Wear it often', 'A signature becomes powerful through repetition and association.'],
        ],
        'cta_title' => 'Find the piece that feels like you',
        'cta_copy' => 'Explore expressive jewellery designed for unforgettable entrances and lasting stories.',
        'cta_href' => 'category.php',
        'cta_label' => 'View Signature Pieces',
    ],
    'gold-purity' => [
        'type' => 'guide',
        'title' => 'Gold Purity',
        'eyebrow' => 'Understanding Karat And Fineness',
        'intro' => 'A straightforward guide to the numbers stamped on gold jewellery and what they mean for colour, composition and wear.',
        'hero' => 'assets/web/gold-dish-model.webp',
        'hero_position' => 'center 38%',
        'statement_label' => 'Reading The Measure',
        'statement_title' => 'Karat describes the proportion of gold in an alloy.',
        'statement_copy' => ['Twenty-four karat represents gold at or close to pure gold. Jewellery is often made in lower karats, combining gold with other metals for colour and practical durability.', 'Fineness expresses the same idea in parts per thousand: 18K corresponds to 750 fineness, while 14K corresponds to 585 fineness.'],
        'feature_image' => 'assets/web/countdown-statement-necklace.webp',
        'feature_label' => 'Purity At A Glance',
        'feature_title' => 'Know the number before choosing the piece.',
        'feature_copy' => 'Higher purity brings a richer gold content and often a deeper yellow tone. Alloy composition and construction also influence hardness, finish and how a piece performs in daily wear.',
        'chapters_title' => 'Common purity levels',
        'chapters' => [
            ['24K / 999', 'Approximately 99.9% Gold', 'Rich in colour and highly malleable; more common in bullion and selected traditional applications.'],
            ['22K / 916', 'Approximately 91.6% Gold', 'A high-gold alloy widely associated with richly coloured jewellery.'],
            ['18K / 750', '75% Gold', 'Balances substantial gold content with versatility for fine settings and regular wear.'],
        ],
        'quote' => 'Purity, construction and intended wear should always be considered together.',
        'notes_title' => 'Before you purchase',
        'notes' => [
            ['Check both formats', 'Purity may be shown as karat, fineness or both, such as 18K and 750.'],
            ['Do not judge by colour alone', 'Alloy metals and surface finishes can change appearance.'],
            ['Review the hallmark', 'For hallmarked jewellery in India, look for the BIS logo, purity mark and HUID.'],
        ],
        'cta_title' => 'Continue learning about gold',
        'cta_copy' => 'Explore colour, alloy, wearability and care in our complete gold guide.',
        'cta_href' => 'gold-guide.php',
        'cta_label' => 'Read The Gold Guide',
    ],
    'hallmark-information' => [
        'type' => 'guide',
        'title' => 'Hallmark Information',
        'eyebrow' => 'Marks Of Assurance',
        'intro' => 'Learn how to read the official marks used to communicate the purity and traceability of hallmarked gold jewellery in India.',
        'hero' => 'assets/web/category-pendants-model.webp',
        'hero_position' => 'center 40%',
        'statement_label' => 'The Indian Hallmark',
        'statement_title' => 'Three marks help identify a hallmarked gold article.',
        'statement_copy' => ['According to the Bureau of Indian Standards, the current hallmark consists of the BIS logo, the purity expressed in karat and fineness, and a six-digit alphanumeric HUID.', 'The HUID is unique to each hallmarked item and can be checked through the Verify HUID feature in the BIS Care app.'],
        'feature_image' => 'assets/web/sculpted-diamond-pendant.webp',
        'feature_label' => 'Read Before You Wear',
        'feature_title' => 'Look closely at the complete set of marks.',
        'feature_copy' => 'A hallmark is an official record of precious-metal fineness. It should be considered alongside the invoice, product description and any stone-related documentation supplied with the piece.',
        'chapters_title' => 'What to look for',
        'chapters' => [
            ['01', 'BIS Logo', 'The Bureau of Indian Standards mark identifies the official hallmarking scheme.'],
            ['02', 'Purity Mark', 'The karat and fineness appear together, for example 22K916 or 18K750.'],
            ['03', 'Six-Digit HUID', 'A unique alphanumeric identifier that can be verified through the BIS Care app.'],
        ],
        'quote' => 'A hallmark communicates metal purity; stone quality and product details require their own documentation.',
        'notes_title' => 'A confident purchase',
        'notes' => [
            ['Inspect the article', 'Ask the jewellery specialist to help you locate and read the marks.'],
            ['Verify the HUID', 'Use the official BIS Care app and its Verify HUID feature.'],
            ['Keep your invoice', 'Retain the purchase record and all accompanying product documents.'],
        ],
        'source_url' => 'https://www.bis.gov.in/hallmarking-overview/hallmarking-faqs/hallmarking-faq/?lang=en',
        'source_label' => 'Official BIS Hallmarking FAQ',
        'cta_title' => 'Understand gold before choosing',
        'cta_copy' => 'Continue with purity, colour and wearability in our complete gold guide.',
        'cta_href' => 'gold-guide.php',
        'cta_label' => 'Explore The Gold Guide',
    ],
    'jewellery-care' => [
        'type' => 'guide',
        'title' => 'Jewellery Care',
        'eyebrow' => 'Preserve The Beauty',
        'intro' => 'Simple, consistent care helps protect surface finish, settings and the quiet brilliance of the jewellery you love.',
        'hero' => 'assets/web/birthstone-occasion-model.webp',
        'hero_position' => 'center 38%',
        'statement_label' => 'Care Begins With Habit',
        'statement_title' => 'Wear thoughtfully. Store separately. Check regularly.',
        'statement_copy' => ['Jewellery naturally gathers traces of wear. Gentle handling and appropriate storage can reduce unnecessary scratches, tangling and exposure to residues.', 'Different metals, stones, pearls and surface treatments may need specialised care. When uncertain, seek professional guidance before cleaning.'],
        'feature_image' => 'assets/web/pearl-necklace-product.webp',
        'feature_label' => 'Before And After Wear',
        'feature_title' => 'Small routines protect fine details.',
        'feature_copy' => 'Apply fragrance, lotion and cosmetics before putting jewellery on. After wear, wipe pieces gently with a clean, soft cloth and allow them to dry before storage.',
        'chapters_title' => 'The essentials',
        'chapters' => [
            ['01', 'Wear', 'Remove jewellery before swimming, strenuous activity or contact with household chemicals.'],
            ['02', 'Clean', 'Use only methods suitable for the specific metal, stone, pearl or finish.'],
            ['03', 'Store', 'Keep pieces dry and separated in soft-lined compartments or individual pouches.'],
        ],
        'quote' => 'The best care is quiet, regular and specific to the materials in your piece.',
        'notes_title' => 'When to seek assistance',
        'notes' => [
            ['A setting feels loose', 'Stop wearing the piece and arrange an inspection before a stone is lost.'],
            ['A clasp changes', 'Resistance, looseness or misalignment can indicate that service is needed.'],
            ['The finish looks different', 'Avoid aggressive polishing; ask about the correct treatment for that surface.'],
        ],
        'cta_title' => 'Need care advice for a specific piece?',
        'cta_copy' => 'Share the material and condition with our team for appropriate next steps.',
        'cta_href' => 'contact.php',
        'cta_label' => 'Contact Client Care',
    ],
    'certification' => [
        'type' => 'guide',
        'title' => 'Certification',
        'eyebrow' => 'Clarity Through Documentation',
        'intro' => 'Understand the different documents that may accompany fine jewellery and the questions each one is designed to answer.',
        'hero' => 'assets/web/exclusive-services-models.webp',
        'hero_position' => 'center 40%',
        'statement_label' => 'Know What The Document Covers',
        'statement_title' => 'Metal, gemstones and the finished piece are not documented in the same way.',
        'statement_copy' => ['A metal hallmark communicates precious-metal fineness. A laboratory report may describe the characteristics of a particular gemstone. A product invoice records the commercial details of your purchase.', 'Read the scope, issuer and identifying information on each document rather than treating every paper as interchangeable certification.'],
        'feature_image' => 'assets/web/diamond-halo-pendant.webp',
        'feature_label' => 'Match The Details',
        'feature_title' => 'Documentation should connect clearly to the item.',
        'feature_copy' => 'Where a report or identification number is provided, review the measurements, description and number against the accompanying jewellery information. Ask how it can be independently verified.',
        'chapters_title' => 'Three useful records',
        'chapters' => [
            ['01', 'Hallmark', 'An official mark communicating the fineness of the precious metal article.'],
            ['02', 'Gemstone Report', 'A laboratory document describing assessed characteristics of the submitted stone.'],
            ['03', 'Purchase Record', 'An invoice or product document describing the item, price and seller.'],
        ],
        'quote' => 'Good documentation makes clear what was assessed, by whom and how it relates to your piece.',
        'notes_title' => 'Questions worth asking',
        'notes' => [
            ['Who issued it?', 'Identify the hallmarking authority, laboratory or seller responsible for the document.'],
            ['What was assessed?', 'Confirm whether the record covers metal purity, a loose stone or the finished article.'],
            ['Can it be verified?', 'Look for a report, hallmark or identification number and an official verification route.'],
        ],
        'cta_title' => 'Choose with clarity',
        'cta_copy' => 'Our guides help you understand the materials and information behind a considered purchase.',
        'cta_href' => 'diamond-guide.php',
        'cta_label' => 'Read The Diamond Guide',
    ],
];
